2013/05/19 23:33:01 [error] [exception.CDbException] exception 'CDbException' with message 'The table "MyModel" for active record class "MyModel" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(MyModel))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('MyModel')
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(30): CActiveRecord->__construct()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facilito/
---
2013/05/19 23:34:17 [error] [exception.CDbException] exception 'CDbException' with message 'The table "mimodelo" for active record class "MyModel" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(MyModel))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('MyModel')
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(30): CActiveRecord->__construct()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facilito/
---
2013/05/20 01:33:56 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.urlSufix" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(220): CComponent->__set('urlSufix', 'html')
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii\framework\base\CApplication.php(510): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/yii/facilito/site/index
HTTP_REFERER=http://localhost/yii/facilito/site/page?view=about
---
2013/05/20 01:34:20 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.urlSufix" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(220): CComponent->__set('urlSufix', 'html')
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii\framework\base\CApplication.php(510): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/yii/facilito/site/index
HTTP_REFERER=http://localhost/yii/facilito/site/page?view=about
---
2013/05/20 01:34:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "contacthtml".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('contacthtml')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contacthtml')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contacthtm...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/contacthtml
HTTP_REFERER=http://localhost/yii/facilito/site/pagehtml?view=about
---
2013/05/20 01:34:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.html".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('index.html')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index.html')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.html')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/index.html
HTTP_REFERER=http://localhost/yii/facilito/site/contact.html
---
2013/05/20 01:35:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page.jsp".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page.jsp')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page.jsp')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page.jsp')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/page.jsp?view=about
HTTP_REFERER=http://localhost/yii/facilito/site/index.jsp
---
2013/05/20 01:35:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page.asp".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page.asp')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page.asp')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page.asp')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/page.asp?view=about
HTTP_REFERER=http://localhost/yii/facilito/site/index.asp
---
2013/05/21 04:12:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(55): UsersController->loadModel('500')
#1 [internal function]: UsersController->actionView('500')
#2 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/facilito/users/500.html
---
2013/05/21 04:35:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(55): UsersController->loadModel('500')
#1 [internal function]: UsersController->actionView('500')
#2 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/facilito/users/500.html
---
2013/05/21 04:35:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/bootstrap.min.css".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/bootstrap.m...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/css/bootstrap.min.css
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:35:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/bootstrap.js".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('js/bootstrap.js')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/js/bootstrap.js
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:35:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.js".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.js')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/js/jquery.js
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:35:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/responsive.min.css".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/responsive....')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/css/responsive.min.css
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:36:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "ico/favicon.png".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ico/favicon.png')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/ico/favicon.png
---
2013/05/21 04:37:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(55): UsersController->loadModel('500')
#1 [internal function]: UsersController->actionView('500')
#2 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/facilito/users/500.html
---
2013/05/21 04:43:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "users".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/users
---
2013/05/21 04:49:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/bootstrap.min.css".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/bootstrap.m...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/css/bootstrap.min.css
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:49:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/bootstrap.js".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('js/bootstrap.js')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/js/bootstrap.js
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:49:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/responsive.min.css".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/responsive....')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/css/responsive.min.css
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:49:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.js".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.js')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/js/jquery.js
HTTP_REFERER=http://localhost/yii/facilito/users/500.html
---
2013/05/21 04:49:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "users".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/users
---
2013/05/21 05:12:23 [error] [exception.CException] exception 'CException' with message 'SiteController contains improperly nested widget tags in its view "C:\xampp\htdocs\yii\facilito\themes\blue\views/site\index.php". A CActiveForm widget does not have an endWidget() call.' in C:\xampp\htdocs\yii\framework\web\CBaseController.php:101
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#2 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(32): CController->render('index')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/site/index.html
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/05/21 12:18:51 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yii\facilito\themes\blue\views\site\index.php:16)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/site/index.html
in C:\xampp\htdocs\yii\facilito\themes\blue\views\site\index.php (16)
in C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/05/21 12:19:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/slide-01.jpg".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('img/slide-01.jp...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/img/slide-01.jpg
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/05/21 12:19:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/slide-02.jpg".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('img/slide-02.jp...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/img/slide-02.jpg
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/05/21 12:19:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/slide-03.jpg".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('img/slide-03.jp...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/img/slide-03.jpg
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/05/21 12:41:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "cont".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('cont')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('cont')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/cont')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/cont
---
2013/05/21 12:43:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "cont".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('cont')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('cont')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/cont')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/cont
---
2013/05/26 02:18:58 [error] [php] include(CountriesController.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(3): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(354): require()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/countries/index
in C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php (3)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/05/31 04:23:28 [error] [php] include(C:\xampp\htdocs\yii\facilito\protected\Gustavo.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:395)
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(7): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CountriesController->actionIndex()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CountriesController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CountriesController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CountriesController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/countries/index.html
in C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php (7)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/05/31 04:23:30 [error] [php] include(C:\xampp\htdocs\yii\facilito\protected\Gustavo.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:395)
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(7): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CountriesController->actionIndex()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CountriesController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CountriesController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CountriesController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/countries/index.html
in C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php (7)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/06/01 05:31:01 [error] [php] include(CApplicationComponents.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\extensions\GHappy.php(3): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\YiiBase.php(314): require()
#2 C:\xampp\htdocs\yii\framework\YiiBase.php(196): import()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(386): createComponent()
#4 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CWebApplication->getComponent()
#5 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(10): CWebApplication->__get()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CountriesController->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CountriesController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CountriesController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CountriesController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/countries/index.html
in C:\xampp\htdocs\yii\facilito\protected\extensions\GHappy.php (3)
in C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php (10)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/06/03 15:54:18 [error] [exception.CException] exception 'CException' with message 'Property "CHttpRequest.basePath" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(9): CComponent->__get('basePath')
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CountriesController->actionIndex()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('countries')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yii/facilito/countries/
---
2013/06/03 16:10:17 [error] [php] Undefined index: HTTP_REFERER (C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): CountriesController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): CountriesController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CountriesController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/countries/
in C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php (19)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/06/03 19:49:57 [error] [exception.CException] exception 'CException' with message 'CWebUser and its behaviors do not have a method or closure named "checkAcces".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:265
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(8): CComponent->__call('checkAcces', Array)
#1 C:\xampp\htdocs\yii\facilito\protected\controllers\CountriesController.php(8): CWebUser->checkAcces('admin')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CountriesController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('countries')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/yii/facilito/countries
---
2013/06/03 19:53:16 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\components\UserIdentity.php(29): CComponent->__set('id', '2')
#1 C:\xampp\htdocs\yii\facilito\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(95): CModel->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/yii/facilito/site/login.html
HTTP_REFERER=http://localhost/yii/facilito/site/login.html
---
2013/06/03 20:04:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/admin.html
HTTP_REFERER=http://localhost/yii/facilito/users
---
2013/06/03 22:06:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/03 22:07:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/03 22:07:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
---
2013/06/03 22:08:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
---
2013/06/03 22:08:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
---
2013/06/03 22:08:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
---
2013/06/03 22:08:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
---
2013/06/03 22:08:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html
---
2013/06/03 22:09:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/03 22:09:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/03 22:11:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/03 22:13:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=admin
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/03 23:01:48 [error] [exception.CException] exception 'CException' with message 'Property "RoleForm.desciption" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(66): CComponent->__get('desciption')
#1 [internal function]: UsersController->actionView('2')
#2 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/facilito/users/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/2.html
---
2013/06/04 00:49:24 [error] [exception.CException] exception 'CException' with message 'Property "CActiveForm.enabledAjaxValidation" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWidgetFactory.php(161): CComponent->__set('enabledAjaxVali...', true)
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(UsersController), 'CActiveForm', Array)
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(189): CBaseController->createWidget('CActiveForm', Array)
#3 C:\xampp\htdocs\yii\facilito\protected\views\users\view.php(38): CBaseController->beginWidget('CActiveForm', Array)
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('view', Array, true)
#8 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(82): CController->render('view', Array)
#9 [internal function]: UsersController->actionView('2')
#10 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#11 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#22 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#23 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/yii/facilito/users/2.html
---
2013/06/04 02:06:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/contact
---
2013/06/04 04:05:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/users.html
HTTP_REFERER=http://localhost/yii/facilito/gii/crud.html
---
2013/06/04 04:06:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/users
---
2013/06/04 04:19:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/users.html
HTTP_REFERER=http://localhost/yii/facilito/gii/crud.html
---
2013/06/04 04:37:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "assign".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('assign')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=adminUser
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 04:37:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('assign')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/assign')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/assign/2.html?item=adminUser
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 04:37:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/users/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 04:50:44 [error] [exception.CException] exception 'CException' with message 'Alias "zii.widgets.jui.CJuiDatePiker" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii\framework\YiiBase.php:316
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWidgetFactory.php(146): YiiBase::import('zii.widgets.jui...', true)
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(UsersController), 'zii.widgets.jui...', Array)
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.jui...', Array)
#3 C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php(47): CBaseController->widget('zii.widgets.jui...', Array)
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\facilito\protected\views\users\update.php(19): CController->renderPartial('_form', Array)
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#12 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(104): CController->render('update', Array)
#13 [internal function]: UsersController->actionUpdate('2')
#14 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/update')
#26 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#27 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/yii/facilito/users/update/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 05:01:33 [error] [exception.CException] exception 'CException' with message 'Users and its behaviors do not have a method or closure named "getMenuCountries".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:265
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(225): CComponent->__call('getMenuCountrie...', Array)
#1 C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php(60): CActiveRecord->__call('getMenuCountrie...', Array)
#2 C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php(60): Users->getMenuCountries()
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\facilito\protected\views\users\update.php(19): CController->renderPartial('_form', Array)
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#11 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(104): CController->render('update', Array)
#12 [internal function]: UsersController->actionUpdate('2')
#13 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#14 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#24 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/update')
#25 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#26 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/yii/facilito/users/update/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 05:03:30 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "checkBoxField".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:265
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php(72): CComponent->__call('checkBoxField', Array)
#1 C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php(72): CActiveForm->checkBoxField(Object(Users), 'status')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\facilito\protected\views\users\update.php(19): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#10 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(104): CController->render('update', Array)
#11 [internal function]: UsersController->actionUpdate('2')
#12 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#23 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/update')
#24 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#25 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/yii/facilito/users/update/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 05:24:54 [error] [php] include(Cities.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\yii\facilito\protected\models\Users.php(118): spl_autoload_call()
#1 C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php(66): Users->getMenuCities()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): UsersController->renderInternal()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(869): UsersController->renderFile()
#5 C:\xampp\htdocs\yii\facilito\protected\views\users\update.php(20): UsersController->renderPartial()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): UsersController->renderInternal()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(869): UsersController->renderFile()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(782): UsersController->renderPartial()
#10 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(104): UsersController->render()
#11 unknown(0): UsersController->actionUpdate()
#12 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\yii\framework\web\CController.php(265): UsersController->runActionWithFilters()
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UsersController->run()
#23 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#25 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/users/update/2.html
in C:\xampp\htdocs\yii\facilito\protected\models\Users.php (118)
in C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php (66)
in C:\xampp\htdocs\yii\facilito\protected\views\users\update.php (20)
2013/06/04 05:25:21 [error] [php] Missing argument 2 for CHtml::listData(), called in C:\xampp\htdocs\yii\facilito\protected\models\Users.php on line 120 and defined (C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php:1836)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): UsersController->renderInternal()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(869): UsersController->renderFile()
#3 C:\xampp\htdocs\yii\facilito\protected\views\users\update.php(20): UsersController->renderPartial()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): UsersController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): UsersController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): UsersController->renderPartial()
#8 C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php(104): UsersController->render()
#9 unknown(0): UsersController->actionUpdate()
#10 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#11 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(265): UsersController->runActionWithFilters()
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UsersController->run()
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#23 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/users/update/2.html
in C:\xampp\htdocs\yii\facilito\protected\models\Users.php (120)
in C:\xampp\htdocs\yii\facilito\protected\views\users\_form.php (66)
in C:\xampp\htdocs\yii\facilito\protected\views\users\update.php (20)
2013/06/04 05:40:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('menuCities')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/menuCitie...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/menuCities.html?_=1370317224931
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/04 05:41:39 [error] [php] Undefined index: Users (C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php:148)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): UsersController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UsersController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/users/menuCities.html?_=1370317299568
in C:\xampp\htdocs\yii\facilito\protected\controllers\UsersController.php (148)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/06/09 18:24:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('citiesByCountry')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/citiesByC...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/citiesByCountry.html
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/09 19:11:25 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yii\facilito\themes\blue\views\site\index.php:8)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/site/index.html
in C:\xampp\htdocs\yii\facilito\themes\blue\views\site\index.php (8)
in C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/06/09 19:19:44 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yii\facilito\themes\blue\views\site\index.php:8)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php(33): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/site/index.html
in C:\xampp\htdocs\yii\facilito\themes\blue\views\site\index.php (8)
in C:\xampp\htdocs\yii\facilito\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2013/06/09 19:25:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "users".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/users
---
2013/06/09 19:59:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/admin/img/slide-01.jpg".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/admin/im...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/themes/admin/img/slide-01.jpg
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/06/09 19:59:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/admin/img/slide-02.jpg".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/admin/im...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/themes/admin/img/slide-02.jpg
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/06/09 19:59:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/admin/img/slide-03.jpg".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/admin/im...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/themes/admin/img/slide-03.jpg
HTTP_REFERER=http://localhost/yii/facilito/site/index.html
---
2013/06/10 04:15:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/update')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/update/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/update/2.html
---
2013/06/10 04:15:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/update')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users/update/2.html
HTTP_REFERER=http://localhost/yii/facilito/users/admin.html
---
2013/06/10 04:15:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/facilito/users
---
2019/07/21 22:34:55 [error] [exception.CException] CException: CAssetManager.basePath "C:\xampp\htdocs\Yii-Facilito\yii-facilito\facilito\assets" is invalid. Please make sure the directory exists and is writable by the Web server process. in C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CAssetManager.php:138
Stack trace:
#0 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CAssetManager.php(123): CAssetManager->setBasePath('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CAssetManager.php(217): CAssetManager->getBasePath()
#2 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CClientScript.php(462): CAssetManager->publish('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CClientScript.php(499): CClientScript->getCoreScriptUrl()
#4 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CClientScript.php(315): CClientScript->getPackageBaseUrl('jquery')
#5 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CClientScript.php(208): CClientScript->renderCoreScripts()
#6 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CController.php(351): CClientScript->render('<!DOCTYPE html>...')
#7 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CController.php(788): CController->processOutput('<!DOCTYPE html>...')
#8 C:\xampp\htdocs\Yii-Facilito\yii-facilito\facilito\protected\controllers\SiteController.php(74): CController->render('contact', Array)
#9 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#10 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CWebApplication.php(282): CController->run('contact')
#14 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#15 C:\xampp\htdocs\Yii-Facilito\yii-facilito\framework\base\CApplication.php(169): CWebApplication->processRequest()
#16 C:\xampp\htdocs\Yii-Facilito\yii-facilito\facilito\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/Yii-Facilito/yii-facilito/facilito/site/contact.html
HTTP_REFERER=http://localhost/yii-facilito/yii-facilito/facilito/site/page.html?view=about
---
